### ISSUE TITLE
State should be metrics, not dimensions

### ISSUE THREAD

**Issue by jakajancar** [sbrudenell/sb8200_exporter#4]
Let's say I want to create a dashboard panel for "Connectivity state". The value should be:

a) null => no data (no color and/or missing data point, e.g. cannot connect to modem)
b) 0 => not connected (red and/or data point at zero)
 c) 1 => connected (green and/or data point at one)

I don't think this is currently queryable. Using the metric `sb8200_state{acquire_downstream_channel_comment="Locked"}`, there is no distinction between (a) and (b) - both are the same.

I would suggest adding the metrics:

  - `sb8200_downstream_channel_locked`
      - 1 if `acquire_downstream_channel_comment == "Locked"`
      - 0 otherwise
  - `sb8200_(connectivity|boot|configuration_file)_ok`
      - 1 if `connectivity_(connectivity|boot|configuration_file)_status == "OK"`
      - 0 otherwise
  - `sb8200_security_enabled`
      - 1 if `security_status == "Enabled"`
      - 0 otherwise
  - `sb8200_docsis_network_access_allowed`
      - 1 if `docsis_network_access_enabled_status == "Allowed"`
      - 0 otherwise

Alternatively, a somewhat more generic solution:

  - `sb8200_{procedure}`
      - 1 if `[status, comment]  intersects ["Locked", "OK", "Enabled", "Allowed"]`
      - 0 otherwise

What do you think?

**Comment by sbrudenell** [comment]
I think there's a strong incentive to minimize the logic in the exporter. We're scraping HTML, not an API, and it's already subtly changed since I originally wrote this code (I guess my modem downloads some firmware updates from Comcast at boot time?). When the HTML changes, it seems nicer to only need to update my dashboard, rather than need to update both my dashboard and the exporter code.

For what it's worth: my approach was to treat all these state values as very black-box. I don't know what "acquire downstream channel = locked" really means, or whether it's sufficient to mean the modem is up. What I really want is just to know when anything changes. So it's sufficient for me to have a grafana panel that just graphs `sb8200_state`, with fill enabled. When state changes, the labels change, and grafana treats it as a new series and gives it a new color. This clearly shows me when the state changed, and hover shows what the state was at any given time.

**Comment by jakajancar** [comment]
Do I get this right?

<img src="https://paste.jaka.io/2019-08-01/Screen%20Shot%202019-08-01%20at%205.46.19%20PM.png">

Seems pretty unreadable to me, but I guess it's good in capturing all changes.

**Comment by jakajancar** [comment]
Managed to avoid the original problem by using e.g.:

    sb8200_state{acquire_downstream_channel_comment="Locked"} or sb8200_state*0

this way the metric is correctly 1, 0 or null.
